version: "3.8"
services:
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Satish#3035
      MYSQL_USER: admin_35
      MYSQL_DATABASE: dragon_1
      MYSQL_PASSWORD: Satish#3035
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database-1.cp08iisywcke.ap-south-1.rds.amazonaws.com
      - DB_USER=admin_35
      - DB_NAME=dragon_1
      - DB_PASSWORD=Satish#3035
    depends_on:
      - database
  frontend:
    build: ./client
    environment:
      - REACT_APP_API_URL=http://15.207.252.191/api
    ports:
      - "3000:80"
    depends_on:
      - backend
